// automatically generated by the FlatBuffers compiler, do not modify

package infcomp.protocol;

public final class Distribution {
  private Distribution() { }
  public static final byte NONE = 0;
  public static final byte Categorical = 1;
  public static final byte Discrete = 2;
  public static final byte Flip = 3;
  public static final byte Normal = 4;
  public static final byte UniformDiscrete = 5;
  public static final byte VMF = 6;
  public static final byte Poisson = 7;
  public static final byte UniformContinuous = 8;
  public static final byte MultivariateNormal = 9;
  public static final byte Laplace = 10;

  public static final String[] names = { "NONE", "Categorical", "Discrete", "Flip", "Normal", "UniformDiscrete", "VMF", "Poisson", "UniformContinuous", "MultivariateNormal", "Laplace", };

  public static String name(int e) { return names[e]; }
}

