// automatically generated by the FlatBuffers compiler, do not modify

package infcomp.protocol;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Gamma extends Table {
  public static Gamma getRootAsGamma(ByteBuffer _bb) { return getRootAsGamma(_bb, new Gamma()); }
  public static Gamma getRootAsGamma(ByteBuffer _bb, Gamma obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Gamma __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double proposalLocation() { int o = __offset(4); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double proposalScale() { int o = __offset(6); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }

  public static int createGamma(FlatBufferBuilder builder,
      double proposal_location,
      double proposal_scale) {
    builder.startObject(2);
    Gamma.addProposalScale(builder, proposal_scale);
    Gamma.addProposalLocation(builder, proposal_location);
    return Gamma.endGamma(builder);
  }

  public static void startGamma(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addProposalLocation(FlatBufferBuilder builder, double proposalLocation) { builder.addDouble(0, proposalLocation, 0.0); }
  public static void addProposalScale(FlatBufferBuilder builder, double proposalScale) { builder.addDouble(1, proposalScale, 0.0); }
  public static int endGamma(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

