// automatically generated by the FlatBuffers compiler, do not modify

package infcomp.protocol;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ObservesInitRequest extends Table {
  public static ObservesInitRequest getRootAsObservesInitRequest(ByteBuffer _bb) { return getRootAsObservesInitRequest(_bb, new ObservesInitRequest()); }
  public static ObservesInitRequest getRootAsObservesInitRequest(ByteBuffer _bb, ObservesInitRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ObservesInitRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public NDArray observes() { return observes(new NDArray()); }
  public NDArray observes(NDArray obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createObservesInitRequest(FlatBufferBuilder builder,
      int observesOffset) {
    builder.startObject(1);
    ObservesInitRequest.addObserves(builder, observesOffset);
    return ObservesInitRequest.endObservesInitRequest(builder);
  }

  public static void startObservesInitRequest(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addObserves(FlatBufferBuilder builder, int observesOffset) { builder.addOffset(0, observesOffset, 0); }
  public static int endObservesInitRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

