// automatically generated by the FlatBuffers compiler, do not modify

package infcomp.protocol;

public final class Reply {
  private Reply() { }
  public static final byte NONE = 0;
  public static final byte TracesFromPriorReply = 1;
  public static final byte ObservesInitReply = 2;
  public static final byte ProposalReply = 3;

  public static final String[] names = { "NONE", "TracesFromPriorReply", "ObservesInitReply", "ProposalReply", };

  public static String name(int e) { return names[e]; }
}

