// automatically generated by the FlatBuffers compiler, do not modify

package infcomp.protocol;

public final class Request {
  private Request() { }
  public static final byte NONE = 0;
  public static final byte TracesFromPriorRequest = 1;
  public static final byte ObservesInitRequest = 2;
  public static final byte ProposalRequest = 3;

  public static final String[] names = { "NONE", "TracesFromPriorRequest", "ObservesInitRequest", "ProposalRequest", };

  public static String name(int e) { return names[e]; }
}

