// automatically generated by the FlatBuffers compiler, do not modify

package infcomp.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class DiscreteProposal extends Table {
  public static DiscreteProposal getRootAsDiscreteProposal(ByteBuffer _bb) { return getRootAsDiscreteProposal(_bb, new DiscreteProposal()); }
  public static DiscreteProposal getRootAsDiscreteProposal(ByteBuffer _bb, DiscreteProposal obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public DiscreteProposal __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int size() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public NDArray probabilities() { return probabilities(new NDArray()); }
  public NDArray probabilities(NDArray obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createDiscreteProposal(FlatBufferBuilder builder,
      int size,
      int probabilitiesOffset) {
    builder.startObject(2);
    DiscreteProposal.addProbabilities(builder, probabilitiesOffset);
    DiscreteProposal.addSize(builder, size);
    return DiscreteProposal.endDiscreteProposal(builder);
  }

  public static void startDiscreteProposal(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addSize(FlatBufferBuilder builder, int size) { builder.addInt(0, size, 0); }
  public static void addProbabilities(FlatBufferBuilder builder, int probabilitiesOffset) { builder.addOffset(1, probabilitiesOffset, 0); }
  public static int endDiscreteProposal(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

