// automatically generated by the FlatBuffers compiler, do not modify

package infcomp.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Discrete extends Table {
  public static Discrete getRootAsDiscrete(ByteBuffer _bb) { return getRootAsDiscrete(_bb, new Discrete()); }
  public static Discrete getRootAsDiscrete(ByteBuffer _bb, Discrete obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Discrete __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int priorSize() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public NDArray proposalProbabilities() { return proposalProbabilities(new NDArray()); }
  public NDArray proposalProbabilities(NDArray obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createDiscrete(FlatBufferBuilder builder,
      int prior_size,
      int proposal_probabilitiesOffset) {
    builder.startObject(2);
    Discrete.addProposalProbabilities(builder, proposal_probabilitiesOffset);
    Discrete.addPriorSize(builder, prior_size);
    return Discrete.endDiscrete(builder);
  }

  public static void startDiscrete(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addPriorSize(FlatBufferBuilder builder, int priorSize) { builder.addInt(0, priorSize, 0); }
  public static void addProposalProbabilities(FlatBufferBuilder builder, int proposalProbabilitiesOffset) { builder.addOffset(1, proposalProbabilitiesOffset, 0); }
  public static int endDiscrete(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

