// automatically generated by the FlatBuffers compiler, do not modify

package infcomp.flatbuffers;

public final class MessageBody {
  private MessageBody() { }
  public static final byte NONE = 0;
  public static final byte TracesFromPriorRequest = 1;
  public static final byte ObservesInitRequest = 2;
  public static final byte ProposalRequest = 3;
  public static final byte TracesFromPriorReply = 4;
  public static final byte ObservesInitReply = 5;
  public static final byte ProposalReply = 6;

  public static final String[] names = { "NONE", "TracesFromPriorRequest", "ObservesInitRequest", "ProposalRequest", "TracesFromPriorReply", "ObservesInitReply", "ProposalReply", };

  public static String name(int e) { return names[e]; }
}

