// automatically generated by the FlatBuffers compiler, do not modify

package infcomp.flatbuffers;

public final class ProposalDistribution {
  private ProposalDistribution() { }
  public static final byte NONE = 0;
  public static final byte UniformDiscreteProposal = 1;
  public static final byte NormalProposal = 2;

  public static final String[] names = { "NONE", "UniformDiscreteProposal", "NormalProposal", };

  public static String name(int e) { return names[e]; }
}

