// automatically generated by the FlatBuffers compiler, do not modify

package infcomp;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TracesFromPriorRequest extends Table {
  public static TracesFromPriorRequest getRootAsTracesFromPriorRequest(ByteBuffer _bb) { return getRootAsTracesFromPriorRequest(_bb, new TracesFromPriorRequest()); }
  public static TracesFromPriorRequest getRootAsTracesFromPriorRequest(ByteBuffer _bb, TracesFromPriorRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public TracesFromPriorRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int numTraces() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createTracesFromPriorRequest(FlatBufferBuilder builder,
      int num_traces) {
    builder.startObject(1);
    TracesFromPriorRequest.addNumTraces(builder, num_traces);
    return TracesFromPriorRequest.endTracesFromPriorRequest(builder);
  }

  public static void startTracesFromPriorRequest(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addNumTraces(FlatBufferBuilder builder, int numTraces) { builder.addInt(0, numTraces, 0); }
  public static int endTracesFromPriorRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

